"""Create initial database tables for banking system

Revision ID: aecd5aee8f3a
Revises: 
Create Date: 2025-08-17 18:54:17.100389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecd5aee8f3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_cards_card_number'), table_name='cards')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_statements_id'), table_name='statements')
    op.drop_index(op.f('ix_statements_statement_number'), table_name='statements')
    op.drop_table('statements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('statement_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('statement_period_start', sa.DATETIME(), nullable=False),
    sa.Column('statement_period_end', sa.DATETIME(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('opening_balance', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('total_deposits', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('total_withdrawals', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('total_fees', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('total_interest', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('total_transactions', sa.INTEGER(), nullable=True),
    sa.Column('deposits_count', sa.INTEGER(), nullable=True),
    sa.Column('withdrawals_count', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('is_generated', sa.BOOLEAN(), nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('generated_at', sa.DATETIME(), nullable=True),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statements_statement_number'), 'statements', ['statement_number'], unique=1)
    op.create_index(op.f('ix_statements_id'), 'statements', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=200), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('routing_number', sa.VARCHAR(length=9), nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=22), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('balance', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('available_balance', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('is_overdraft_protected', sa.BOOLEAN(), nullable=True),
    sa.Column('overdraft_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('daily_transfer_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('daily_withdrawal_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_activity', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=1)
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('card_number', sa.VARCHAR(length=16), nullable=False),
    sa.Column('card_type', sa.VARCHAR(length=7), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('cardholder_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('expiry_month', sa.INTEGER(), nullable=False),
    sa.Column('expiry_year', sa.INTEGER(), nullable=False),
    sa.Column('cvv_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_pin_set', sa.BOOLEAN(), nullable=True),
    sa.Column('pin_hash', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_contactless_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_international_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('daily_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('monthly_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('credit_limit', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_index(op.f('ix_cards_card_number'), 'cards', ['card_number'], unique=1)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('from_account_id', sa.INTEGER(), nullable=True),
    sa.Column('to_account_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('merchant_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('merchant_category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('balance_before', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('balance_after', sa.NUMERIC(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DATETIME(), nullable=True),
    sa.Column('settled_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=1)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###
